config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :foods
	root 'home#index'

	get 'menu' => 'home#index'
	get 'contact' => 'home#contact_us'
	get 'contact_us' => 'home#contact_us'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :price, :section, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	section = params[:section]
  	sort = params[:sort]
    search = params[:search]

  	if section
  		@foods = Food.where(section: section)
  	else
  		@foods = Food.all
  	end

  	if search
      @foods.each do |food|
        if food.name.include? search
        else
          @foods = @foods - [food]
        end
      end
    end

    if sort
  		case sort
  			when 'alphabetical'
  				@foods = @foods.order('name asc')
  			when 'low2high'
  				@foods = @foods.order('price asc')
  			when 'high2low'
  				@foods = @foods.order('price desc')
  		end
  	end

  end

  def contact_us
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @food = Food.find(@order.food_id)
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.food_id = params[:food].to_i
    @food = Food.find(params[:food])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Thank you for your order page.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :phone, :address, :food_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/foods/_form.html.erb
<%= form_for(food) do |f| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :section %>
    <%= f.text_field :section %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= food.price %></td>
        <td><%= food.section %></td>
        <td><%= food.image %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-4">
<h1><%= @food.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
  <span>VND</span>
</p>

<p>
  <strong>Delivery cost:</strong>
  <span>20,000 VND</span>
</p>

<p>
  <strong>Section:</strong>
  <%= @food.section %>
</p>

<p>
  <%= link_to "Make order", "/orders/new?food=" + @food.id.to_s, class: "btn btn-warning" %>
</p>
<br/>
</div>
<div class="col-sm-8">
<img src="<%= @food.image %>">
</div>

app/views/home/contact_us.html.erb
<div class="col-sm-4">
<h1>Contact Us</h1>
<p>Address: 146 Từ Hoa Công Chúa, Hanoi, Vietnam</p>
<p>Contact: <a href="tel:0123456789">0123456789</a></p>
<p>Email: <a href="mailto:info.theleprechaun@gmail.com">info.theleprechaun@gmail.com</a></p>
<br/>
</div>
<div class="col-sm-8">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.3671868791794!2d105.82714415004322!3d21.057991892087916!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135aa55979bfc1b%3A0xe5c3992a2a20403e!2zMTQ2IFThu6sgSG9hIEPDtG5nIENow7phLCBRdeG6o25nIEFuLCBUw6J5IEjhu5MsIEjDoCBO4buZaSwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1476365930390" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

app/views/home/index.html.erb
<section id="nav-section">
<div class="btn-group btn-group-justified" role="group">
<% {'breakfast' => 'Breakfast', 'lunch' => 'Lunch', 'dinner' => 'Dinner', 'drink' => 'Drinks'}.each do |key, value| %>

	<% if params[:section] == key %>
		<%= link_to value, root_path(:section => key, :sort => params[:sort]), class: 'btn btn-primary' %>
	<% else %>
		<%= link_to value, root_path(:section => key, :sort => params[:sort]), class: 'btn btn-secondary' %>
	<% end %>

<% end %>
</div>
<br/>
<div class="btn-group btn-group-justified" role="group">
<% {'alphabetical' => 'Alphabetical', 'low2high' => 'Price Low to High', 'high2low' => 'Price High to Low'}.each do |key, value| %>

	<% if params[:sort] == key %>
		<%= link_to value, root_path(:sort => key, :section => params[:section]), class: 'btn btn-primary' %>
	<% else %>
		<%= link_to value, root_path(:sort => key, :section => params[:section]), class: 'btn btn-secondary' %>
	<% end %>

<% end %>
</div>
</section>

<section id="food-section">
	<% i = 0 %>
	<% @foods.each do |f| %>
		<div class="food-item">
			<% i = i + 1 %>
			<p><%=i%>. <%= link_to f.name, f %> </p>
			<p> Price: <%= f.price %><span> VND</span></p>
			<p> Section: <%= f.section %></p>
			<img src="<%=f.image%>">
		</div>
	<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to The Leprechaun</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<header>
	<nav class="container navbar navbar-light bg-faded">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to "Leprechaun", root_path, class: "navbar-brand" %></li>
			<li class="nav-item"><%= link_to "Menu", root_path, class: "nav-link" %></li>
			<li class="nav-item"><%= link_to "Contact Us", contact_us_path, class: "nav-link" %></li>
		</ul>
    <%= form_tag root_path, method: 'get', class: 'form-inline pull-xs-right', role: 'search' do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control"%>
      <%= submit_tag "Search", class: 'btn btn-warning' %>
    <% end %>
	</nav>

	</header>
  <section class="container">
    <%= yield %>
  </section>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone, class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control"%>
  </div>

  <div class="field food-id-field">
    <%= f.label :food_id %>
    <%= f.text_field :food_id %>
  </div>

  <div class="actions">
    <%= f.submit "Make Order", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.phone %></td>
        <td><%= order.address %></td>
        <td><%= order.food %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="col-sm-6">
<h1>New Order: <%= @food.name %></h1>

<%= render 'form', order: @order%>
</div>
<div class="col-sm-6">
<img src="<%= @food.image %>">
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-sm-4">
<p>
  <strong>Food:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= (@food.price + 20000).to_s %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Ordered at:</strong>
  <%= @order.created_at %>
</p>
</div>
<div class="col-sm-8">
<img src="<%= @food.image %>">
</div>